### ISSUE TITLE
[] in dnsNames column for certificates with no SANs

### ISSUE THREAD

**Issue by titanous** [alex/revocation-tracker#5]
For example, certificate 179755654.

**Comment by alex** [comment]
Hmmm, so that cert has a SAN, it just has no dNSName entries. What would be better?

**Comment by titanous** [comment]
A couple options (not mutually exclusive)

- Expand the column to include IP addresses.
- _none_ (not highlighted with `<code>`)

**Comment by alex** [comment]
So I'm pretty sure it'll display `None` if there's no SAN, and `[]` if there's no dNSNames.

I'll make it at least not do `[]`.

**Comment by titanous** [comment]
Makes sense, ensuring that the `None` isn't highlighted so it's distinguishable would be nice (could make it italic as well to be even more obvious that it's a special non-value).
